name: orientai
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- AGGIUNGI QUESTE RIGHE QUI SOTTO ---
  cupertino_icons: ^1.0.6
  
  # Firebase (Il Backend)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  
  # Gemini (L'Intelligenza Artificiale)
  google_generative_ai: ^0.4.6
  flutter_markdown: ^0.7.7+1
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.2.0
  # ---------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  mocktail: ^1.0.0

flutter:
  uses-material-design: true